# Use postgres/example user/password credentials
# docker compose -f docker-compose-postgre.yml up -d
version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: es-b3-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    command:
      postgres -c maintenance_work_mem=512MB
    ports:
      - "5432:5432"