services:
  postgres:
    image: postgres:latest
    container_name: db_postgres
    env_file: .env.base
    command: ["postgres", "-c", "maintenance_work_mem=512MB"]
    ports:
      - "5432:5432"

  backend:
    image: es-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_sprint1
    env_file: .env.base
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    image: es-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_sprint1
    env_file: .env.base
    ports:
      - "8000:8000"
    depends_on:
      - backend