services:
  postgres:
    image: postgres:latest
    container_name: db_postgres
    command: ["postgres", "-c", "maintenance_work_mem=512MB"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "es-b3-database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"

  backend:
    image: es-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_sprint1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: "db_postgres"
      DB_NAME: "es-b3-database"
      DB_PASSWORD: "12345"
      DB_PORT: "5432"
      DB_USERNAME: "user"
      SW_HOST: "localhost"
      SW_PORT: "3000"
      MAIL_USER: "moviemate@zohomail.eu"
      MAIL_PASS: "Movie@1234ADJLMN"
      SECRET_KEY: "ES-UB-B3"

  frontend:
    image: es-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_sprint1
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      VUE_APP_API_BASE_URL: "http://localhost:3000"
