name: Autograding

on:
  pull_request:
    branches:
      - develop
      - pre-production
      - main
  push:
    branches:
      - develop
      - pre-production
      - main

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run autograding tests
      run: |
        docker-compose up -d
        docker exec backend_sprint1 sh -c "npm run test:integration_users"